services:
  - type: web
    name: sleep-outside-team-04
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: BACKEND_URL
        value: https://wdd330-backend.onrender.com
      - key: ALLOW_CORS
        value: "false"
        sync: false
      - key: PORT
        sync: false
